### ISSUE TITLE
Server showing menu.PreparingSpawn instead of Preparing Spawn Area

### ISSUE THREAD

**Issue by gamerpotion** [tristankechlo/Tool-Leveling#29]
Not sure if this is a bug or how it will affect things in-game, but when using ToolLeveling on a server, it changes the Preparing Spawn area text to menu.PreparingSpawn

**Without ToolLeveling**:-

```
[12:57:38 INFO]: Preparing start region for dimension minecraft:overworld
[12:57:39 INFO]: Preparing spawn area: 0%
[12:57:39 INFO]: Preparing spawn area: 0%
[12:57:39 INFO]: Preparing spawn area: 0%
[12:57:40 INFO]: Preparing spawn area: 0%
[12:57:40 INFO]: Preparing spawn area: 14%
[12:57:41 INFO]: Preparing spawn area: 96%
[12:57:41 INFO]: Time elapsed: 2797 ms
[12:57:41 INFO]: Done (3.533s)! For help, type "help"
```

**With ToolLeveling**:-

```
[12:51:18 INFO]: Preparing start region for dimension minecraft:overworld
[12:51:19 INFO]: menu.preparingSpawn
[12:51:19 INFO]: menu.preparingSpawn
[12:51:19 INFO]: menu.preparingSpawn
[12:51:20 INFO]: menu.preparingSpawn
[12:51:20 INFO]: menu.preparingSpawn
[12:51:21 INFO]: Time elapsed: 2564 ms
[12:51:21 INFO]: Done (2.952s)! For help, type "help"

```

Have tested this with just the mod enabled and disabled.   Is there a way to fix this so we can see the percentage status in the log?
something to do with the language file?

**Comment by gamerpotion** [comment]
Sorry should have mentioned, am using toolleveling-1.18.1-1.3.0.jar   but on Fabric 1.18.2

**Comment by tristankechlo** [comment]
I know of this issue, it will not effect any ingame translations  
This is fixed in 1.19 already, will do this for 1.18.2 in the next few days

**Comment by gamerpotion** [comment]
> I know of this issue, it will not effect any ingame translations This is fixed in 1.19 already, will do this for 1.18.2 in the next few days

Thanks, not sure if applied in new update?  as its still showing that message.

**Comment by tristankechlo** [comment]
Which version did you try, cause it is fixed for me in 1.19-1.3.2

**Comment by gamerpotion** [comment]
> Which version did you try, cause it is fixed for me in 1.19-1.3.2

Hi, I need it updated for 1.18.2 please. So 1.18.2 version with that translation fix that would be helpful.

**Comment by tristankechlo** [comment]
check out the newest version for 1.18.2, should be fixed now

**Comment by gamerpotion** [comment]
Thank you it seems like its working now
